# Site settings
title: ENAE788M
#email: yiannis@cs.umd.edu
description: "Course materials and notes for University of Maryland's class ENAE788M."
baseurl: ""
url: "http://prgaero.github.io"
#github_username:  cmsc733

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge


theme: jekyll-theme-cayman
